version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: ${COMPOSE_PROJECT_NAME}_app
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql
      - redis

  node:
    build:
      context: ./node
    container_name: ${COMPOSE_PROJECT_NAME}_node
    working_dir: /var/www/store
    volumes:
      - ./app:/var/www
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:1.25-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  mysql:
    image: mysql:8.3
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    environment:
      # MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

  redis:
    image: redis:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_redis

volumes:
  db-data: